version: '3.7'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ../sites/:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx/
      - ./nginx/sites-allowed/:/etc/nginx/sites-allowed/
    tty: true
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    networks:
      - default
  php:
    build:
      context: ./php
    container_name: php
    volumes:
      - ../sites/:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-php.ini
    ports:
      - "9001:9001"
    depends_on:
      - mysql
    networks:
      - default
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: "mysql"
    command: --character-set-server=utf8mb4 --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: Symfony123!
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - default
#  rabbitmq:
#    image: "rabbitmq:3-management"
#    hostname: "rabbit"
#    container_name: rabbitmq
#    labels:
#      NAME: "rabbitmq"
#    volumes:
#      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
#    ports:
#      - "15672:15672"
#    networks:
#      - default
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: "zookeeper"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181'
    networks:
      - default
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    hostname: "kafka"
    depends_on:
      - zookeeper
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - default
  redis:
    image: "redis:latest"
    command: redis-server /usr/local/etc/redis/redis.conf
    hostname: "redis"
    container_name: redis
    volumes:
      - ./redis/data/:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - default
networks:
  default:
    driver: bridge